
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS ID LPAREN MINUS NUMBER PLUS PRINT RPAREN TIMESprogram : stmt_liststmt_list : stmt stmt_list\n| stmtstmt : declaration\n| assignment\n| print_stmtdeclaration : ID EQUALS exprassignment : ID EQUALS exprprint_stmt : PRINT IDexpr : expr PLUS expr\n| expr MINUS expr\n| expr TIMES expr\n| expr DIVIDE exprexpr : NUMBERexpr : ID'
    
_lr_action_items = {'ID':([0,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[7,7,-4,-5,-6,11,12,-9,-15,-7,-14,12,12,12,12,-10,-11,-12,-13,]),'PRINT':([0,3,4,5,6,11,12,13,14,19,20,21,22,],[8,8,-4,-5,-6,-9,-15,-7,-14,-10,-11,-12,-13,]),'$end':([1,2,3,4,5,6,9,11,12,13,14,19,20,21,22,],[0,-1,-3,-4,-5,-6,-2,-9,-15,-7,-14,-10,-11,-12,-13,]),'EQUALS':([7,],[10,]),'NUMBER':([10,15,16,17,18,],[14,14,14,14,14,]),'PLUS':([12,13,14,19,20,21,22,],[-15,15,-14,15,15,15,15,]),'MINUS':([12,13,14,19,20,21,22,],[-15,16,-14,16,16,16,16,]),'TIMES':([12,13,14,19,20,21,22,],[-15,17,-14,17,17,17,17,]),'DIVIDE':([12,13,14,19,20,21,22,],[-15,18,-14,18,18,18,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([0,3,],[2,9,]),'stmt':([0,3,],[3,3,]),'declaration':([0,3,],[4,4,]),'assignment':([0,3,],[5,5,]),'print_stmt':([0,3,],[6,6,]),'expr':([10,15,16,17,18,],[13,19,20,21,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt_list','program',1,'p_program','parser.py',6),
  ('stmt_list -> stmt stmt_list','stmt_list',2,'p_stmt_list','parser.py',10),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list','parser.py',11),
  ('stmt -> declaration','stmt',1,'p_stmt','parser.py',18),
  ('stmt -> assignment','stmt',1,'p_stmt','parser.py',19),
  ('stmt -> print_stmt','stmt',1,'p_stmt','parser.py',20),
  ('declaration -> ID EQUALS expr','declaration',3,'p_declaration','parser.py',24),
  ('assignment -> ID EQUALS expr','assignment',3,'p_assignment','parser.py',28),
  ('print_stmt -> PRINT ID','print_stmt',2,'p_print_stmt','parser.py',32),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop','parser.py',36),
  ('expr -> expr MINUS expr','expr',3,'p_expr_binop','parser.py',37),
  ('expr -> expr TIMES expr','expr',3,'p_expr_binop','parser.py',38),
  ('expr -> expr DIVIDE expr','expr',3,'p_expr_binop','parser.py',39),
  ('expr -> NUMBER','expr',1,'p_expr_number','parser.py',43),
  ('expr -> ID','expr',1,'p_expr_id','parser.py',47),
]
